name: Sanity Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Bazel
      run: |
        wget https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-installer-linux-x86_64.sh
        chmod +x bazel-3.7.2-installer-linux-x86_64.sh
    
    - name: Install Bazel
      run: |
        sudo ./bazel-3.7.2-installer-linux-x86_64.sh
    
    - name: Update System
      run: |
        sudo apt-get update
    
    - name: Install Build Dependencies
      run: |
        sudo apt-get install -y build-essential g++-aarch64-linux-gnu gcc-aarch64-linux-gnu qemu-efi-aarch64 qemu-system-aarch64 qemu-utils binutils-aarch64-linux-gnu

    - name: Build Project
      run: |
        make

    - name: Run SelfDependentW4A4 Test
      run: |
        qemu-aarch64-static ./low_precision_fully_connected_test test-gemm-api SelfDependentW4A4

    - name: Run SelfDependentW4A8 Test
      run: |
        qemu-aarch64-static ./low_precision_fully_connected_test test-gemm-api SelfDependentW4A8

    - name: Run BarrelShiftMultiplierW8A8 Test
      run: |
        qemu-aarch64-static ./low_precision_fully_connected_test test-gemm-api BarrelShiftMultiplierW8A8


